version: '3.5'

services:
  telegram-watcher:
    #build: .
    image: <IMAGE_NAME>
    container_name: <CONTAINER_NAME>
    read_only: true
    environment:
      # See the Telegram API settings: https://my.telegram.org/apps
      TELEGRAM_API_ID: <API_ID>
      TELEGRAM_API_HASH: <API_HASH>
      TELEGRAM_API_STRING: <API_STRING_SESSION>
      TELEGRAM_RECIPIENT_ID: -100<GROUP_CHANNEL_ID>
      TELEGRAM_BOT_API_HASH: <BOT_API_HASH>
    
